spring.application.name=SocialMedia

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=java_social_media_9toq_user
spring.datasource.password=C5ipC7zAv2wlhRuUkwccNh9nrb2Tz7Hl
spring.datasource.url=jdbc:postgresql://dpg-d8k9ibe7r5hc73dmbjsg-a.oregon-postgres.render.com/java_social_media_9toq

spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=ALWAYS