spring.application.name=SocialMedia

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d9b6uc58nd3s73a9ur0g-a.oregon-postgres.render.com/java_social_media_cgd5
spring.datasource.username=java_social_media_cgd5_user
spring.datasource.password=IAGtboGDl4qJMEsYMjMOtso9mS2o5AEB
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.output.ansi.enabled=ALWAYS

springdoc.swagger-ui.path=/swagger-ui.html
